config/routes.rb
Rails.application.routes.draw do
  get '/about', to: 'static_pages#about'
  get '/contact', to: 'static_pages#contact'
  get '/help', to: 'static_pages#help'
  get '/profile', to: 'static_pages#profile'
  # resources :bonsai_items
  # resources :carts
  resources :bonsais do
    resources :reviews
  end

  devise_for :users, controllers: {
    registrations: 'registrations',
    omniauth_callbacks: 'omniauth_callbacks'
  }
  devise_scope :user do
    get "registrations/user_profile" => "registrations#user_profile"
  end
  # get 'registrations/user_profile', to:'registrations#user_profile', as: 'user_profile'
  get 'bonsais/cart', to:'bonsais#cart_path', as: 'cart_path'
  get 'bonsais/add_to_cart/:id', to:'bonsais#add_to_cart', as: 'add_to_cart'
  get 'bonsais/remove_from_cart/:id', to: 'bonsais#remove_from_cart', as: 'remove_from_cart'
  # delete 'bonsais/remove_from_cart/:id', to: 'bonsais#remove_from_cart', as: 'remove_from_cart'

  root :to => 'bonsais#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/cart.rb
class Cart < ApplicationRecord
    # has_many :bonsai_items, dependent: :destroy

    # def add_bonsai(bonsai) 
    #     current_item = bonsai_items.find_by(bonsai_id: bonsai.id)

    #     if bonsai_item
    #         current_item.increment(:quantity)
    #     else
    #         current_item = bonsai_items.build(bonsai_id: bonsai.id)
    #     end
    #     current_item
    # end

    # def total_price 
    #     bonsai.price.to_a.sum {|bonsai| bonsai.total_price}
    # end

end

app/controllers/carts_controller.rb
# class CartsController < ApplicationController
    
#     before_action :set_cart, only: [:show, :edit, :update, :destroy] 
#     rescue_from ActiveRecord::RecordNotFound, with: :invalid_cart
    

#     def index 
#         @carts = Cart.all 
#     end

#     def show 

#     end

#     def new 
#         @cart = Cart.new
#     end

#     def edit 

#     end

#     def create
#         @cart = Cart.new(cart_params)

#         respond_to do |format|
#             if @cart.save
#                 format.html { redirect_to @cart, notice: 'Cart was successfully created.' }
#                 format.json { render :show, status: :created, location: @cart }
#             else
#                 format.html { render :new }
#                 format.json { render json: @cart.errors, status: :unprocessable_entity }
#             end
#         end
#     end

#     def update
#         respond_to do |format|
#             if @cart.update(cart_params)
#                 format.html { redirect_to @cart, notice: 'Cart was successfully updated.' }
#                 format.json { render :show, status: :ok, location: @cart }
#             else
#                 format.html { render :edit }
#                 format.json { render json: @cart.errors, status: :unprocessable_entity }
#             end
#         end
#     end

#     def destroy
#         @cart.destroy if @cart.id == session[:cart_id]
#         session[:cart_id] = nil
#         respond_to do |format|
#             format.html { redirect_to root_path, notice: 'Cart was successfully deleted.' }
#             format.json { head :no_content }
#     end



#     private

#     # Use callbacks to share common setup or constraints between actions.
#     def set_cart
#       @cart = Cart.find(params[:id])
#     end

#     # parameters, only allow the white list through.
#     def cart_params
#       params.fetch(:cart, {})
#     end

#     def invalid_cart
#       logger.error "Attempt to access invalid cart #{params[:id]}"
#       redirect_to root_path, notice: "That cart doesn't exist"
#     end

# end

app/views/carts/index.html.erb
<!-- <p id="notice"><%= notice %></p>

<h1>Carts</h1>

<table>
    <thead>
        <tr>
            <th colspan="3"></th>
        </tr>
    </thead>

    <tbody>
        <% @carts.each do |cart| %>
        <tr>
            <td><%= link_to 'Show', cart %></td>
            <td><%= link_to 'Edit', edit_cart_path(cart) %></td>
            <td><%= link_to 'Destroy', cart, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
        <% end %>
    </tbody>
</table>

<br>

<%= link_to 'New Cart', new_cart_path %> -->

app/views/carts/new.html.erb
<!-- <h1>New Cart</h1>

<%= render 'form', cart: @cart %>

<%= link_to 'Back', carts_path %> -->

app/views/carts/show.html.erb
<!-- <div class="keep-shopping pv1 mt4 has-text-right">
    <%= link_to 'Keep Shopping', bonsais_path, class: 'button is-warning' %>
</div>
<hr />
<section class="section">
    <%= render(@cart.bonsai_items) %>

    <div class="columns">
        <div class="column">
            <%= button_to 'Empty Cart', @cart, method: :delete, data: { confirm: "Are you sure? " }, class: "button is-danger" %>
        </div>
        <div class="column total has-text-right">
            <h4 class="title is-4">
                <span class="f5 has-text-grey">Total:</span> <%= number_to_currency(@cart.total_price) %>
            </h4>
        </div>
    </div>
</section> -->