config/routes.rb
Rails.application.routes.draw do
  get '/about', to: 'static_pages#about'
  get '/contact', to: 'static_pages#contact'
  get '/help', to: 'static_pages#help'
  get '/profile', to: 'static_pages#profile'
  # resources :bonsai_items
  # resources :carts
  resources :bonsais do
    resources :reviews
  end

  devise_for :users, controllers: {
    registrations: 'registrations',
    omniauth_callbacks: 'omniauth_callbacks'
  }
  devise_scope :user do
    get "registrations/user_profile" => "registrations#user_profile"
  end
  # get 'registrations/user_profile', to:'registrations#user_profile', as: 'user_profile'
  get 'bonsais/cart', to:'bonsais#cart_path', as: 'cart_path'
  get 'bonsais/add_to_cart/:id', to:'bonsais#add_to_cart', as: 'add_to_cart'
  get 'bonsais/remove_from_cart/:id', to: 'bonsais#remove_from_cart', as: 'remove_from_cart'
  # delete 'bonsais/remove_from_cart/:id', to: 'bonsais#remove_from_cart', as: 'remove_from_cart'

  root :to => 'bonsais#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
    before_action :set_review, only: [:show, :edit, :update, :destroy]
    before_action :set_bonsai
    before_action :authenticate_user!

    def new 
        @review = Review.new
    end

    def edit 

    end 

    def show 

    end

    def index
        @reviews = Review.all
    end

    def create 
        @review = Review.new(review_params)
        @review.bonsai_id = @bonsai.id
        @review.user_id = current_user.id

        if @review.save
            redirect_to @bonsai
        else
            render 'new'
        end
    end

    def update 
        if @review.update(review_params)
            redirect_to @bonsai
        else 
            render 'edit'
        end
    end

    def destroy 
        @review.destroy
        redirect_to bonsai_path
    end

private

    def review_params
        params.require(:review).permit(:rating, :comment)
    end
    def set_bonsai
        @bonsai = Bonsai.find(params[:bonsai_id])
    end
    def set_review
      @review = Review.find(params[:id])
    end

end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/reviews/_form.html.erb
<div class="field-form">

<%= simple_form_for([@bonsai, @review]) do |f| %>
    <div id="rating-form">
    <%= f.input :rating %>
    </div>
    
    <%= f.input :comment, as: :text, :input_html => { :cols => 75, :rows => 2 } %>
    <%= f.button :submit, "Submit Your Review", class: "button is-warning" %>
<% end %>

</div>
<div><%= link_to 'Back', bonsai_path(@bonsai) %></div>

app/views/reviews/_review.html.erb
<div class="review-block">

<p><%= review.rating %></p>
<p> <%= review.comment %></p>
<p class="has-text-gray fg pt1">Reviewed by: <%= review.user.name %></p>

<% if user_signed_in? %>

    <% if review.user_id == current_user.id %>
        <%= link_to "Edit", edit_bonsai_review_path(review.bonsai, review) %>
    <% end %>
<% end %>
</div>

app/views/reviews/edit.html.erb
<h1 class="title">Editing Review</h1>
<h4 class="subtitle is-4"><strong>Bonsai your Editing:</strong> <%= @bonsai.name %></h4>

<div class="edit-review-form">

    <%= simple_form_for([@bonsai, @review]) do |f| %>
    <%= f.input :rating %>
    <%= f.input :comment, as: :text, :input_html => { :cols => 75, :rows => 2 } %>
    <%= f.button :submit, :class => "button is-warning" %>
    <% end %>

</div>
<div><%= link_to 'Back', bonsai_path(@bonsai) %></div>

app/views/reviews/index.html.erb
<!-- Bonsai reviews for: <h1 class="title is-2"><%= @bonsai.name %></h1> -->

<!-- <div class="review-space">
    <h3 class="subtitle is-4">Reviews:</h3>
    <%= render @bonsai.reviews %>
</div> -->

<div class="container">
    <div class="notification">

        Bonsia Reviews for : <h2 class="title is-3"><%= @bonsai.name %></h2>
        <br>
        <div class="columns is-multiline is-centered">

            <table class="table is-bordered is-striped is-narrow is-hoverable is-large">

                <thead>
                    <tr>
                        <th>Rating </th>
                        <th>Comment</th>
                    </tr>
                </thead>
                <tbody>

                    <% @bonsai.reviews.each do |review| %>
                    <tr>
                        <td><%= review.rating %></td>
                        <td><%= review.comment %></td>

                        <% end %>
                    </tr>
                </tbody>
            </table>

        </div>
        <h2><%= link_to "Go Back", :back %></h2>
    </div>
</div>

app/views/reviews/new.html.erb
<h1 class="title"> Add a New Review </h1>

<h4 class="subtitle is-4"><strong>Bonsai your Reviewing:</strong> <%= @bonsai.name %></h4>


<%= render 'form' %>

app/views/reviews/show.html.erb
<h2>Sorry no reviews here!</h2>