config/routes.rb
Rails.application.routes.draw do
  get '/about', to: 'static_pages#about'
  get '/contact', to: 'static_pages#contact'
  get '/help', to: 'static_pages#help'
  get '/profile', to: 'static_pages#profile'
  # resources :bonsai_items
  # resources :carts
  resources :bonsais do
    resources :reviews
  end

  devise_for :users, controllers: {
    registrations: 'registrations',
    omniauth_callbacks: 'omniauth_callbacks'
  }
  devise_scope :user do
    get "registrations/user_profile" => "registrations#user_profile"
  end
  # get 'registrations/user_profile', to:'registrations#user_profile', as: 'user_profile'
  get 'bonsais/cart', to:'bonsais#cart_path', as: 'cart_path'
  get 'bonsais/add_to_cart/:id', to:'bonsais#add_to_cart', as: 'add_to_cart'
  get 'bonsais/remove_from_cart/:id', to: 'bonsais#remove_from_cart', as: 'remove_from_cart'
  # delete 'bonsais/remove_from_cart/:id', to: 'bonsais#remove_from_cart', as: 'remove_from_cart'

  root :to => 'bonsais#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/bonsai.rb
class Bonsai < ApplicationRecord
    # before_destroy :not_referenced_by_any_bonsai_item
    
    mount_uploader :image, ImageUploader
    serialize :image, JSON

    has_many :reviews, dependent: :delete_all
    has_many :users, through: :reviews

    belongs_to :user, optional: true
    # has_many :bonsai_items

    validates :name, :type_of, :price, presence: true
    validates :description, length: {maximum: 1000, too_long: "%{count} characters is the maximum allowed. "}


    TYPE = %w{ Outdoor Indoor Beginner Flowering DYI }

     # added scopes to differentiate bonsai types
    scope :bonsai_type, -> (plant_type) { where("type_of = ?", plant_type).limit(4) }

    # Individual Scopes
    # scope :bonsai_indoor, -> {where(type_of: "Indoor")}
    # scope :bonsai_outdoor, -> {where(type_of: "Outdoor")}

    scope :new_first, -> { order(created_at: :desc) }


    private

    def not_referenced_by_any_bonsai_item
        unless bonsai_items.empty?
            errors.add(:base, "Bonsai items present")
            throw :abort
        end
    end

end

app/controllers/bonsais_controller.rb
class BonsaisController < ApplicationController
    before_action :authenticate_user!, except: [:index, :show]
    before_action :initialize_session
    before_action :set_bonsai, only: [:show, :edit, :update, :destroy]
    before_action :load_cart
   

    def index 
        @bonsais = Bonsai.all.new_first
    end

    def show 
       
    end

    def new 
        @bonsai = current_user.bonsais.build
    end

    def edit 

    end

    def create

        @bonsai = current_user.bonsais.build(bonsai_params)

        respond_to do |format|
            if @bonsai.save
                format.html { redirect_to @bonsai, notice: 'Your Bonsai was successfully created.' }
                format.json { render :show, status: :created, location: @bonsai }
            else
                format.html { render :new }
                format.json { render json: @bonsai.errors, status: :unprocessable_entity }
            end
        end
        
    end

    def update 
        respond_to do |format|
            if @bonsai.update(bonsai_params)
                format.html { redirect_to @bonsai, notice: 'Your Bonsai was successfully updated.' }
                format.json { render :show, status: :created, location: @bonsai }
            else
                format.html { render :new }
                format.json { render json: @bonsai.errors, status: :unprocessable_entity }
            end
        end
    end

    def destroy
        @bonsai.destroy
            respond_to do |format|
            format.html { redirect_to root_path, notice: 'Bonsai was successfully repotted elsewhere.' }
            format.json { head :no_content }
            end
    end

    

    private

    def initialize_session
        session[:cart] ||= []
    end
    def load_cart 
        @cart = Bonsai.find(session[:cart])
    end

    def set_bonsai
        @bonsai = Bonsai.find(params[:id])
    end

    def bonsai_params
        params.require(:bonsai).permit(:name, :type_of, :description, :price, :rating, :image, :user_id )
    
    end


end

app/helpers/bonsais_helper.rb
module BonsaisHelper

  def bonsai_author(bonsai)
    user_signed_in? && current_user.id == bonsai.user_id
  end

end

app/views/bonsais/_cart.html.erb
<details class="details-reset details-with-dialog mt-4">
    <summary class="button is-black">Cart</summary>
    <details-dialog class="details-dialog anim-fade-in fast wide" aria-label="Dialog">
        <div class="Box d-flex flex-column">
            <br>
            <div class="box-header">
                Cart Details
            </div>
            <br>
            <!-- <div class="Box-body overflow-auto"> -->
                <table class="table is-bordered is-striped is-narrow is-hoverable is-fullwidth">
                    <thead>
                        <tr>
                            <th> Bonsai Plant </th>
                
                            <th>Price</th>
                            <th colspan="3"></th>
                        </tr>
                    </thead>
                
                    <tbody>
                        <% @cart.each do |bonsai| %>
                        <tr>
                            <td><%= bonsai.name %></td>
                            <td><%= bonsai.price %></td>
                            <td><%= link_to 'Remove Bonsai', remove_from_cart_path(bonsai), method: :get %></td>
                            <% end %>
                
                            </td>
                
                        </tr>
                        
                    </tbody>
                </table>

        </div>
    </details-dialog>
</details>

app/views/bonsais/_cart4.html.erb
<details class="details-reset details-with-dialog mt-4">
    <summary class="button is-black">Cart</summary>
    <details-dialog class="details-dialog anim-fade-in fast wide" aria-label="Dialog">
        <div class="Box d-flex flex-column">
            <br>
            <div class="box-header">
                Cart Details
            </div>
            <br>
            <!-- <div class="Box-body overflow-auto"> -->
                <table class="table is-bordered is-striped is-narrow is-hoverable is-fullwidth">
                    <thead>
                        <tr>
                            <th> Bonsai Plant </th>
                
                            <th>Price</th>
                            <th colspan="3"></th>
                        </tr>
                    </thead>
                
                    <tbody>
                        <% @cart.each do |bonsai| %>
                        <tr>
                            <td><%= bonsai.name %></td>
                            <td><%= bonsai.price %></td>
                            <td><%= link_to 'Remove Bonsai', remove_from_cart_path(bonsai), method: :get %></td>
                            <% end %>
                
                            </td>
                
                        </tr>
                        
                    </tbody>
                </table>

        </div>
    </details-dialog>
</details>

app/views/bonsais/_flash4.html.erb
<% if flash.now[:notice] %>
<div class="notification is-success global-notification">
    <p class="notice"><%= notice %></p><%= link_to "Remove", "" %>
</div>
<% end %>
<% if flash[:alert] %>
<div class="notification is-danger global-notification">
    <p class="alert"><%= alert %></p><%= link_to "Remove", "" %>
</div>
<% end %>

app/views/bonsais/_form.html.erb
<%= simple_form_for @bonsai, html: { multipart: true } do |f| %>
<%= f.error_notification %>

<div class="columns">

    <div class="column is-6">
        <div class="control">
            <%= f.input :name, required: true, input_html: { class: "input"}, wrapper: false, label_html: { class:"label" } %>
        </div>
    </div>

    <div class="column">
        <div class="control">
            <%= f.input :price, required: true, input_html: { class:"input", maxlength: 7  }, wrapper: false, label_html: { class:"label" } %>
        </div>
    </div>

</div>

<div class="column">
    <div class="control">
        <%= f.input :description, required: true, input_html: { class:"textarea" }, wrapper: false, label_html: { class:"label" } %>
    </div>
</div>

<div class="field">
    <div class="field column is-8">
        <div class="field is-horizontal">
            <label class="label">Bonsai Type</label>
            <div class="control has-icons-left">
                <span class="select">
                    <%= f.input_field :type_of, collection: Bonsai::TYPE, prompt: "Select type" %>
                </span>
                <span class="icon is-small is-left">
                    <i class="fa fa-tag"></i>
                </span>
            </div>
        </div>
    </div>

    <div class="file has-name is-fullwidth">
        <div class="control-images">
            <label class="label">Add Image</label>
            <div class="file">
                <label class="file-label">
                    <%= f.input :image, as: :file, input_html: { class:"file-input bonsai-image" }, label: false, wrapper: false %>
                    <span class="file-cta">
                        <span class="file-icon"><i class="fa fa-upload"></i></span>
                        <span class="file-label">
                            Choose a File…..
                        </span>
                    </span>
                    <span class="file-name">
                        bonsai-picture.png
                    </span>
                </label>
            </div>
        </div>
    </div>
    <output id="list"></output>
    <hr />

    <div class="column">
        <div class="control">
            <%= f.button :submit, class: 'button is-success' %>
            <%= link_to 'Cancel', bonsais_path, class:'button is-light' %>
        </div>
    </div>

    <% end %>

app/views/bonsais/edit.html.erb
<div class="columns">
    <div class="column is-8 is-centered">

        <%= simple_form_for @bonsai, html: { multipart: true } do |f| %>
        <%= f.error_notification %>

        <div class="columns">

            <div class="field column is-6">
                <div class="control">
                    <%= f.input :name, required: true, input_html: { class: "input"}, wrapper: false, label_html: { class:"label" } %>
                </div>
            </div>

            <div class="field column">
                <div class="control">
                    <%= f.input :price, required: true, input_html: { class:"input", maxlength: 7  }, wrapper: false, label_html: { class:"label" } %>
                </div>
            </div>

        </div>

        <div class="field">
            <div class="control">
                <%= f.input :description, required: true, input_html: { class:"textarea" }, wrapper: false, label_html: { class:"label" } %>
            </div>
        </div>

        <div class="field column is-6">
            <div class="control">
                <%= f.input :type_of, required: true, input_html: { class: "input"}, wrapper: false, label_html: { class:"label" } %>
            </div>
        </div>

        <div class="field">
            <div class="control">
                <label class="label">Add images</label>
                <div class="file">
                    <label class="file-label">
                        <%= f.input :image, as: :file, input_html: { class:"file-input bonsai-image" }, label: false, wrapper: false %>
                        <span class="file-cta">
                            <span class="file-icon"><i class="fa fa-upload"></i></span>
                            <span class="file-label">
                                Choose a file…</span>
                            </span>
                    </label>
                </div>
            </div>
        </div>
        
        <hr />
        <div class="columns">
            
            <div class="column">
                <div class="control">
                    <%= f.button :submit, class: 'button is-success' %>
                    <%= link_to 'Cancel', bonsais_path, class:'button is-light' %>
                </div>
                <% end %>
            </div>

        </div>
            
    </div>
        
</div>

app/views/bonsais/index.html.erb
<div class="pa3">
    <div class="scc3">
        <%= render 'layouts/cart' %>
    </div>
</div>
<div class="block">
    <h3 class="title is-3">Indoor Bonsai</h3>
    <div class="bonsai-index-grid pt2 ">
        <% @bonsais.bonsai_type('Indoor').each do |bonsai| %>

        <div class="bonsai border-light">
            <div class="bonsai-thumb">

                <%= link_to image_tag(bonsai.image_url(:thumb)), bonsai %>

                <div class="type_of">
                    <span class="tag is-dark"><%= bonsai.type_of %></span>
                </div>

            </div>

            <div class="pa3">

                <h3 class="fw7 f4 title"><%= link_to bonsai.name, bonsai %></h3>


                <p class="has-text-gray fg pt1">Sold by: <%= bonsai.user.name %></p>

                <p class="f3 fw6 has-text-right pt2 price"><%= number_to_currency(bonsai.price) %></p>



                <% if bonsai_author(bonsai) %>
                <%= link_to 'Edit', edit_bonsai_path(bonsai), class: "button is-small" %>
                <!-- <%= link_to 'Delete', bonsai, method: :delete, data: { confirm: "Are you sure ?" }, class: "button is-small" %> -->
                <% end %>

            </div>
        </div>
        <% end %>
    </div>
</div>
<div class="block">
    <h3 class="title is-3">Outdoor Bonsai</h3>
    <div class="bonsai-index-grid pt2 ">
        <% @bonsais.bonsai_type('Outdoor').each do |bonsai| %>

        <div class="bonsai border-light">
            <div class="bonsai-thumb">

                <%= link_to image_tag(bonsai.image_url(:thumb)), bonsai %>

                <div class="type_of">
                    <span class="tag is-dark"><%= bonsai.type_of %></span>
                </div>

            </div>

            <div class="pa3">

                <h3 class="fw7 f4 title"><%= link_to bonsai.name, bonsai %></h3>


                <p class="has-text-gray fg pt1">Sold by: <%= bonsai.user.name %></p>

                <p class="f3 fw6 has-text-right pt2 price"><%= number_to_currency(bonsai.price) %></p>



                <% if bonsai_author(bonsai) %>
                <%= link_to 'Edit', edit_bonsai_path(bonsai), class: "button is-small" %>
                <!-- <%= link_to 'Delete', bonsai, method: :delete, data: { confirm: "Are you sure ?" }, class: "button is-small" %> -->
                <% end %>

            </div>
        </div>
        <% end %>
    </div>
</div>
<div class="block">
    <h3 class="title is-3">Beginner Bonsai</h3>
    <div class="bonsai-index-grid pt2 ">
        <% @bonsais.bonsai_type('Beginner').each do |bonsai| %>

        <div class="bonsai border-light">
            <div class="bonsai-thumb">

                <%= link_to image_tag(bonsai.image_url(:thumb)), bonsai %>

                <div class="type_of">
                    <span class="tag is-dark"><%= bonsai.type_of %></span>
                </div>

            </div>

            <div class="pa3">

                <h3 class="fw7 f4 title"><%= link_to bonsai.name, bonsai %></h3>


                <p class="has-text-gray fg pt1">Sold by: <%= bonsai.user.name %></p>

                <p class="f3 fw6 has-text-right pt2 price"><%= number_to_currency(bonsai.price) %></p>



                <% if bonsai_author(bonsai) %>
                <%= link_to 'Edit', edit_bonsai_path(bonsai), class: "button is-small" %>
                <!-- <%= link_to 'Delete', bonsai, method: :delete, data: { confirm: "Are you sure ?" }, class: "button is-small" %> -->
                <% end %>

            </div>
        </div>
        <% end %>
    </div>
</div>

<div class="block">
    <h3 class="title is-3">Flowering Bonsai</h3>
    <div class="bonsai-index-grid pt2 ">
        <% @bonsais.bonsai_type('Flowering').each do |bonsai| %>

        <div class="bonsai border-light">
            <div class="bonsai-thumb">

                <%= link_to image_tag(bonsai.image_url(:thumb)), bonsai %>

                <div class="type_of">
                    <span class="tag is-dark"><%= bonsai.type_of %></span>
                </div>

            </div>

            <div class="pa3">

                <h3 class="fw7 f4 title"><%= link_to bonsai.name, bonsai %></h3>


                <p class="has-text-gray fg pt1">Sold by: <%= bonsai.user.name %></p>

                <p class="f3 fw6 has-text-right pt2 price"><%= number_to_currency(bonsai.price) %></p>



                <% if bonsai_author(bonsai) %>
                <%= link_to 'Edit', edit_bonsai_path(bonsai), class: "button is-small" %>
                <!-- <%= link_to 'Delete', bonsai, method: :delete, data: { confirm: "Are you sure ?" }, class: "button is-small" %> -->
                <% end %>

            </div>
        </div>
        <% end %>
    </div>
</div>

app/views/bonsais/new.html.erb
<div class="columns">
    <div class="column is-8 is-centered">
        <%= simple_form_for @bonsai, html: { multipart: true } do |f| %>
        <%= f.error_notification %>
        
        <div class="columns">
        
            <div class="field column is-6">
                <div class="control">
                    <%= f.input :name, required: true, input_html: { class: "input"}, wrapper: false, label_html: { class:"label" } %>
                </div>
            </div>
        
            <div class="column">
                <div class="control">
                    <%= f.input :price, required: true, input_html: { class:"input", maxlength: 7  }, wrapper: false, label_html: { class:"label" } %>
                </div>
            </div>
        
        </div>
        
        <div class="column">
            <div class="control">
                <%= f.input :description, required: true, input_html: { class:"textarea" }, wrapper: false, label_html: { class:"label" } %>
            </div>
        </div>

        <div class="column">
            <div class="control">
                <%= f.hidden_field :user_id, :value => current_user.id %>
            </div>
        </div>
        
        <div class="field">
            <div class="field column is-8">
                <div class="field is-horizontal">
                    <label class="label">Bonsai Type</label>
                    <div class="control has-icons-left">
                        <span class="select">
                            <%= f.input_field :type_of, collection: Bonsai::TYPE, prompt: "Select type" %>
                        </span>
                        <span class="icon is-small is-left">
                            <i class="fa fa-tag"></i>
                        </span>
                    </div>
                </div>
            </div>
        
            <div class="file has-name is-fullwidth">
                <div class="control-images">
                    <label class="label">Add Image</label>
                    <div class="file">
                        <label class="file-label">
                            <%= f.input :image, as: :file, input_html: { class:"file-input bonsai-image" }, label: false, wrapper: false %>
                            <span class="file-cta">
                                <span class="file-icon"><i class="fa fa-upload"></i></span>
                                <span class="file-label">
                                    Choose a File…..
                                </span>
                            </span>
                            <span class="file-name">
                                bonsai-picture.png
                            </span>
                        </label>
                    </div>
                </div>
            </div>
        
            <hr />
        
            <div class="column">
                <div class="control">
                    <%= f.button :submit, class: 'button is-success', :user_id => session[:user_id] %>
                    <%= link_to 'Cancel', bonsais_path, class:'button is-light' %>
                </div>
            </div> 
        
            <% end %>

    </div>
</div>

app/views/bonsais/show.html.erb
<% content_for :body_class, 'bg-light' %>

<section class="section instrument-show">
    <div class="columns">
        <div class="column is-8">
            <h3 class="title "><%= @bonsai.name %></h3>

            <div class="content pa4 mt3 bg-white border-radius-3">

                <h3 class="subtitle is-4">Type of Bonsai:</h3>
                <%= @bonsai.type_of %>

                <h3 class="subtitle is-4">Price of Bonsai:</h3>
                <%= @bonsai.price %>

                <!-- <div class="content pa4 mt3 bg-white border-radius-3"> -->

                <h3 class="subtitle is-4">Description:</h3>
                <%= @bonsai.description %>


                <div class="feature-image">
                    <% if @bonsai.image_url %>
                    <%= image_tag(@bonsai.image_url(:main)) %>
                    <% end %>
                </div>

                <div class="review-space">
                    <h3 class="subtitle is-4">Positive Reviews:</h3>
                    <%= render @bonsai.reviews.positive %>
                </div>
                <div class="columns">
                    <div class="column">
                        <div class="add-review">
                            <%= link_to "Add Review", new_bonsai_review_path(@bonsai) %>
                        </div>
                    </div>
                    <div class="column">
                        <div class="add-review">
                            <%= link_to "See All Reviews", bonsai_reviews_path(@bonsai) %>
                        </div>
                    </div>
                </div>

                <div class="columns">
                    <div class="column">
                        <% if @cart.include?(@bonsai) %>
                        <p>Bonsai is in Cart.</p>
                        <!-- <p> <%= link_to 'remove from cart', remove_from_cart_path(@bonsai),  method: :get %> </p> -->
                        <% else %>
                        <%= link_to 'Add to Cart', add_to_cart_path(@bonsai.id), method: :get,  class: 'button is-large is-warning add-to-cart' %>
                        <% end %>
                    </div>
                    <div class="column">
                        <%= link_to 'Home', root_path, class: "button is-small" %>
                        <% if bonsai_author(@bonsai) %>
                        <%= link_to 'Edit', edit_bonsai_path(@bonsai), class: "button is-small" %>
                        <%= link_to 'Destroy', bonsai_path(@bonsai), method: :delete, class: "button is-small" %>
                        <% end %>
                    </div>
                </div>
            </div>
        </div>
    </div>

</section>