config/routes.rb
Rails.application.routes.draw do
  get '/about', to: 'static_pages#about'
  get '/contact', to: 'static_pages#contact'
  get '/help', to: 'static_pages#help'
  get '/profile', to: 'static_pages#profile'
  # resources :bonsai_items
  # resources :carts
  resources :bonsais do
    resources :reviews
  end

  devise_for :users, controllers: {
    registrations: 'registrations',
    omniauth_callbacks: 'omniauth_callbacks'
  }
  devise_scope :user do
    get "registrations/user_profile" => "registrations#user_profile"
  end
  # get 'registrations/user_profile', to:'registrations#user_profile', as: 'user_profile'
  get 'bonsais/cart', to:'bonsais#cart_path', as: 'cart_path'
  get 'bonsais/add_to_cart/:id', to:'bonsais#add_to_cart', as: 'add_to_cart'
  get 'bonsais/remove_from_cart/:id', to: 'bonsais#remove_from_cart', as: 'remove_from_cart'
  # delete 'bonsais/remove_from_cart/:id', to: 'bonsais#remove_from_cart', as: 'remove_from_cart'

  root :to => 'bonsais#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/_cart.html.erb
<details class="details-reset details-with-dialog mt-4">
    <summary class="button is-black">Cart</summary>
    <details-dialog class="details-dialog anim-fade-in fast wide" aria-label="Dialog">
        <div class="Box d-flex flex-column">
            <br>
            <div class="box-header">
                Cart Details
            </div>
            <br>
            <!-- <div class="Box-body overflow-auto"> -->
            <table class="table is-bordered is-striped is-narrow is-hoverable is-fullwidth">
                <thead>
                    <tr>
                        <th> Bonsai Plant </th>

                        <th>Price</th>
                        <th colspan="3"></th>
                    </tr>
                </thead>

                <tbody>
                    <% @cart.each do |bonsai| %>
                    <tr>
                        <td><%= bonsai.name %></td>
                        <td><%= bonsai.price %></td>
                        <td><%= link_to 'Remove Bonsai', remove_from_cart_path(bonsai), method: :get %></td>
                        <% end %>

                        </td>

                    </tr>
                    <!-- <h2>Subtotal: <%= Bonsai.sum(:price) %></h2> -->
                </tbody>
            </table>

            <!-- </div> -->
            <!-- <div class="Box-footer">
                <button type="button" class="btn btn-block" data-close-dialog>Close</button>
            </div> -->
        </div>
    </details-dialog>
</details>

app/views/layouts/_nav.html.erb
<nav class="navbar is-light" role="navigation" aria-label="main navigation">
    <div class="navbar-brand">
        <%= link_to root_path, class:"navbar-item" do %>
        <h1 class="title is-5">Bonsai Plants</h1>
        <% end  %>
        <!-- <div class="navbar-burger burger" data-target="navbar">
          <span></span>
          <span></span>
          <span></span>
        </div> -->
    </div>
    <a class="navbar-item">
        <%= link_to 'About Us', about_path, class: "navbar-item" %>
    </a>

    <a class="navbar-item">
        <%= link_to 'Contact Us', contact_path, class: "navbar-item" %>
    </a>

    <a class="navbar-item">
        <%= link_to 'FAQs', help_path, class: "navbar-item" %>
    </a>

    <!-- <div id="navbar" class="navbar-menu"> -->
    <div class="navbar-end">
        <div class="navbar-item">


            <% if user_signed_in? %>



            <%= link_to 'Sell a Bonsai', new_bonsai_path, class: "navbar-item button is-dark" %>
            <div class="navbar-item has-dropdown is-hoverable">
                <%= link_to 'Account', edit_user_registration_path, class: "navbar-link" %>
                <div class="navbar-dropdown is-right">
                    <%= link_to current_user.name, edit_user_registration_path, class:"navbar-item" %>

                    <%= link_to registrations_user_profile_path, class:"navbar-item", :method => :get do %> My Reviews <% end %>

                    <%= link_to destroy_user_session_path, class:"navbar-item", :method => :get do %> Log Out!! <% end %>

                </div>
            </div>
            <% else %>
            <div class="field is-grouped">
                <p class="control">
                    <%= link_to "Sign In", new_user_session_path, class:"navbar-item button is-primary" %>
                </p>
                <p class="control">
                    <%= link_to "GitHub", user_github_omniauth_authorize_path, class: "navbar-item button fa fa-github" %>
                </p>
                <p class="control">
                    <%= link_to "Sign up", new_user_registration_path, class:"navbar-item button is-dark" %>
                </p>
            </div>
            <% end %>

        </div>
    </div>
    </div>
    </div>
</nav> 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <title>BonsaiEcom</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag 'application.css', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  <%= stylesheet_link_tag 'https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css' %>
  <!-- <script src="https://kit.fontawesome.com/68cb87669c.js"></script> -->


</head>

<body class="<%= yield (:body_class) %>">

  <%= render 'layouts/flash' %>
  <%= render 'layouts/nav' %>

  <body>
    <div class="hero-class">
      <section class="hero is-primary">
        <div class="hero-body">
          <div class="container">
            <h1 class="title">
              The Bonsai Store
            </h1>
            <h2 class="subtitle">
              World Class Bonsai Delivered to Your Door!
            </h2>
          </div>
        </div>

      </section>
    </div>

    <%= yield %>

    <footer class="footer">
      <div class="container">
        <div class="content has-text-centered">
          <p>
            <strong>Bonsai Ecom</strong> by David J Forer
          </p>
        </div>
      </div>
    </footer>
    <script type="text/javascript" src="https://unpkg.com/@github/include-fragment-element@latest"></script>
  </body>

</html>